package com.boeingmerryho.business.paymentservice.application;

import org.springframework.data.domain.Page;

import com.boeingmerryho.business.paymentservice.application.dto.request.PaymentApproveRequestServiceDto;
import com.boeingmerryho.business.paymentservice.application.dto.request.PaymentDetailRequestServiceDto;
import com.boeingmerryho.business.paymentservice.application.dto.request.PaymentDetailSearchRequestServiceDto;
import com.boeingmerryho.business.paymentservice.application.dto.request.PaymentMembershipCancelRequestServiceDto;
import com.boeingmerryho.business.paymentservice.application.dto.request.PaymentReadyRequestServiceDto;
import com.boeingmerryho.business.paymentservice.application.dto.request.PaymentTicketCancelRequestServiceDto;
import com.boeingmerryho.business.paymentservice.application.dto.response.PaymentApproveResponseServiceDto;
import com.boeingmerryho.business.paymentservice.application.dto.response.PaymentDetailResponseServiceDto;
import com.boeingmerryho.business.paymentservice.application.dto.response.PaymentMembershipCancelResponseServiceDto;
import com.boeingmerryho.business.paymentservice.application.dto.response.PaymentReadyResponseServiceDto;
import com.boeingmerryho.business.paymentservice.application.dto.response.PaymentTicketCancelResponseServiceDto;

public interface PaymentService {
	PaymentReadyResponseServiceDto pay(PaymentReadyRequestServiceDto requestServiceDto);

	PaymentApproveResponseServiceDto approvePayment(PaymentApproveRequestServiceDto requestServiceDto);

	PaymentTicketCancelResponseServiceDto cancelTicketPayment(PaymentTicketCancelRequestServiceDto requestServiceDto);

	PaymentMembershipCancelResponseServiceDto cancelMembershipPayment(
		PaymentMembershipCancelRequestServiceDto requestServiceDto);

	PaymentDetailResponseServiceDto getPaymentDetail(PaymentDetailRequestServiceDto requestServiceDto);

	Page<PaymentDetailResponseServiceDto> searchPaymentDetail(PaymentDetailSearchRequestServiceDto requestServiceDto);
}
